### PR TITLE
feat: add option of launch.sh to avoid unknown flags issue

### LINKED ISSUE #107: -d (daemon) is optional among ther docker-compose version
## Summary
The "Docker COMPOSE" (AKA, DOCKER -COMPOSE) command supports a daemon mode called -D.
However, this option is different for each version. Therefore, I think that it is efficient to ensure that the execution of the launch.sh files is basically executed as a foreground.
And then, If we need to run in the background, we can be able to support the "$ launch.sh -d" format.

## How to reproduce this issue
`ubuntu$ ./launch.sh`

## Screenshot:

image (1)

### PR DESCRIPTION
**Pull request by leemgs**
This PR is to add an option function for the user to selectively use foreground mode and background mode (i.e., daemon mode). Also, depending on the version of docker composer, the -d (daemon mode) option may or may not be present. Therefore, this is to deal effectively with these situations.

Resolved #107 

Signed-off-by: Geunsik Lim <leemgs@gmail.com>
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
RESEND V2.

**Comment by leemgs** [comment]
@moyix  Are you able to review this PR?

**Comment by moyix** [comment]
Whoops, lost track of this one. I will have a look this weekend :)

**Comment by moyix** [comment]
Finally got to this :) I made a couple small fixes but otherwise it looks good, thanks for the contribution!

**Pull request merged**
